### ISSUE TITLE
RX580 not detected RC4

### ISSUE THREAD

**Issue by NLHybrid** [mozkomor/GrinGoldMiner#56]
I'm running Ubuntu-Mate
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.1 LTS
Release:	18.04
Codename:	bionic

Do I need to add my gpu in manual_config?

Unhandled Exception: System.DllNotFoundException: Unable to load shared library 'nvcuda' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: libnvcuda: cannot open shared object file: No such file or directory
   at ManagedCuda.DriverAPINativeMethods.DeviceManagement.cuDeviceGetCount(Int32& count)
   at ManagedCuda.CudaContext.GetDeviceCount() in /home/travis/build/surban/managedCuda/ManagedCUDA/CudaContext.cs:line 5385
   at CudaSolver.Program.Main(String[] args) in /home/photon/ggm_BETA3/GrinGoldMiner/src/CudaSolver/Program.cs:line 148
Detected 0 suitable nvidia devices
**Detected 0 suitable AMD devices**
No devices auto-detected, please use manual config (see readme)
Select minig pool (press number):
[1] Custom stratum address
[2] US-east grinmint.com
[3] EU-west grinmint.com
[4] mwgrinpool.com (open-source, currently invite only)

**Comment by killua99** [comment]
I'm stuck with the same error, did you manage to solve it? with manual config did it work?

**Comment by NLHybrid** [comment]
> I'm stuck with the same error, did you manage to solve it? with manual config did it work?

I'm not sure how to properly input the my gpu in through manual config. Maybe installing AMDGPU-PRO drivers will yield different results.
